export const browserCoreExamples = [
  "openbot browser status",
  "openbot browser start",
  "openbot browser stop",
  "openbot browser tabs",
  "openbot browser open https://example.com",
  "openbot browser focus abcd1234",
  "openbot browser close abcd1234",
  "openbot browser screenshot",
  "openbot browser screenshot --full-page",
  "openbot browser screenshot --ref 12",
  "openbot browser snapshot",
  "openbot browser snapshot --format aria --limit 200",
  "openbot browser snapshot --efficient",
  "openbot browser snapshot --labels",
];

export const browserActionExamples = [
  "openbot browser navigate https://example.com",
  "openbot browser resize 1280 720",
  "openbot browser click 12 --double",
  'openbot browser type 23 "hello" --submit',
  "openbot browser press Enter",
  "openbot browser hover 44",
  "openbot browser drag 10 11",
  "openbot browser select 9 OptionA OptionB",
  "openbot browser upload /tmp/file.pdf",
  'openbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openbot browser dialog --accept",
  'openbot browser wait --text "Done"',
  "openbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openbot browser console --level error",
  "openbot browser pdf",
];
